### ISSUE TITLE
Add Readme

### ISSUE THREAD

**Issue by HeadClot** [CSharpForUnrealEngine5/CsToCpp#1]
Hey @jcoder58 - 

First off excellent work on brining C# to Unreal Engine 5.  

Would it be possible to add a readme.md detailing setup of the plugin? 

I have no idea if this supports the launcher version of Unreal engine. Let alone what engine version.

Thank you for your time,
Benjamin

**Comment by jcoder58** [comment]
It supports the launcher version, but only 5.2.

I suggest git clone one of the examples to start.

Jerome

**Comment by HeadClot** [comment]
Got it thank you so much. :)
